# -*- coding: utf-8 -*-
"""Colurization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fq6267nOZIykBGezWZHzhBOLZdW50a7-
"""

!pip install numpy

!pip install opencv-python

from google.colab.patches import cv2_imshow
 import cv2

import numpy as np
import cv2

prototxt_path='/content/colorization_deploy_v2.prototxt'
model_path='/content/colorization_release_v2.caffemodel'
kernel_path='/content/pts_in_hull.npy'
image_path='/content/tiger.jpg'
#image2_path='/content/flower.jpg'

nnw=cv2.dnn.readNetFromCaffe(prototxt_path,model_path) #nnw is neural network with the trained model path prototxt
points=np.load(kernel_path)

points=points.transpose().reshape(2,313,1,1)
nnw.getLayer(nnw.getLayerId("class8_ab")).blobs=[points.astype(np.float32)] #lab -->lightness *a *b colur scheme

nnw.getLayer(nnw.getLayerId("conv8_313_rh")).blobs=[np.full([1,313],2.606, dtype="float32")]

bw_image=cv2.imread(image1_path)

normalized=bw_image.astype("float32")/255.0

lab=cv2.cvtColor(normalized,cv2.COLOR_BGR2LAB)

resized=cv2.resize(lab,(224,224))
L=cv2.split(resized)[0]
L -=50

nnw.setInput(cv2.dnn.blobFromImage(L))
ab=nnw.forward()[0,:,:,:].transpose((1,2,0))

ab=cv2.resize(ab,(bw_image.shape[1],bw_image.shape[0]))

L=cv2.split(lab)[0]
colorized=np.concatenate((L[:,:,np.newaxis],ab),axis=2)
colorized=cv2.cvtColor(colorized,cv2.COLOR_LAB2BGR)
colorized=(255.0 * colorized).astype("uint8")

import cv2

cv2_imshow(bw_image)
cv2_imshow(colorized)

cv2.waitKey(0)
cv2.destroyAllWindows()